---
abstract: "all you want to do with parameters for your program (or someone else's)"
author:
  - 'Thomas Orgis <thomas@orgis.org>'
build_requires:
  File::Spec: 0
  Storable: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.39
dynamic_config: 1
generated_by: 'Module::Build version 0.3901, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Config-Param
provides:
  Config::Param:
    file: lib/Config/Param.pm
    version: 3.000010
  Config::Param::FileWorker:
    file: lib/Config/Param/FileWorker.pm
    version: 0
requires:
  perl: 5.008
resources:
  license: http://dev.perl.org/licenses/
version: 3.000010
